# Pandas

# 🐼 Pandas Basics

Pandas is a Python library used for:

- Data Analysis
- Data Cleaning
- Data Manipulation
- Reading and Writing CSV/Excel files
- Filtering and Sorting data
- Grouping data
- Handling Missing Values

## Important Pandas Objects

| Object | Description |
|--------|-------------|
| Series | One-dimensional data |
| DataFrame | Two-dimensional tabular data |

The standard way to import Pandas is:

```python
import pandas as pd

# 1. Series

A Series is a **one-dimensional labeled array**.

It is similar to a single column in an Excel sheet.

### Syntax

```python
pd.Series(data)

In [2]:

import pandas as pd


marks = pd.Series([80, 75, 90, 65])

print(marks)

0    80
1    75
2    90
3    65
dtype: int64

# 2. Series with Custom Index

We can provide our own index labels while creating a Series.

In [3]:
marks = pd.Series(
    [80, 75, 90],
    index=["Rahul", "Amit", "Raj"]
)

print(marks)

Rahul    80
Amit     75
Raj      90
dtype: int64

### Access Series Value

In [4]:
print(marks["Rahul"])

80

# 3. DataFrame

A DataFrame is a **two-dimensional table** containing rows and columns.

It is similar to an Excel spreadsheet or a database table.

### Example

| Name | Age | Salary |
|------|-----|--------|
| Rahul | 25 | 50000 |
| Amit | 30 | 60000 |
| Raj | 28 | 55000 |

In [5]:
data = {
    "Name": ["Rahul", "Amit", "Raj"],
    "Age": [25, 30, 28],
    "Salary": [50000, 60000, 55000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000
2    Raj   28   55000

## Understanding `pd.DataFrame(data)`

```python
df = pd.DataFrame(data)
pd.DataFrame(data)
│  │          │
│  │          └── Data we want to put into the table
│  └───────────── Creates a DataFrame
└──────────────── Pandas library


Here:

pd → Pandas library
DataFrame → Pandas class used to create a table
data → Data that we want to store in the DataFrame
df → Variable that stores the DataFrame

# 4. head() and tail()

### head()

`head()` displays the first 5 rows by default.

```python
df.head()

In [6]:
df.head(2)

    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000

### tail() displays the last 5 rows by default.

In [7]:
df.tail()

    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000
2    Raj   28   55000

### We can also specify the number:

In [8]:
df.tail(2)

   Name  Age  Salary
1  Amit   30   60000
2   Raj   28   55000

### Difference between head() and tail(): The head() method returns the first n rows of the DataFrame, while the tail() method returns the last n rows of the DataFrame. By default, both methods return 5 rows if no argument is provided.

In [12]:




print(df.head())
print("Now we can specify the number of rows to display using the head() method:")
print(df.head(2))
print(" We can also specify the number of rows to display using the tail() method:")
print(df.tail())
print("Difference between head() and tail(): The head() method returns the first n rows of the DataFrame, while the tail() method returns the last n rows of the DataFrame. By default, both methods return 5 rows if no argument is provided.")
print(df.tail(2))

    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000
2    Raj   28   55000
Now we can specify the number of rows to display using the head() method:
    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000
 We can also specify the number of rows to display using the tail() method:
    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000
2    Raj   28   55000
Difference between head() and tail(): The head() method returns the first n rows of the DataFrame, while the tail() method returns the last n rows of the DataFrame. By default, both methods return 5 rows if no argument is provided.
   Name  Age  Salary
1  Amit   30   60000
2   Raj   28   55000

# 5. shape

`shape` returns the number of rows and columns.

### Syntax

```python
df.shape

In [13]:
(3, 3)

(3, 3)

means:

3 rows
3 columns

# 6. columns, index and dtypes

### columns

Returns all column names.

```python
df.columns

index

Returns row indexes.

In [14]:
df.index

RangeIndex(start=0, stop=3, step=1)

dtypes

Returns the datatype of each column.

In [15]:
df.dtypes

Name        str
Age       int64
Salary    int64
dtype: object

### " here columns,index and dtypes are attributes of the DataFrame. They provide information about the structure and data types of the DataFrame."

In [18]:
print(" here columns,index and dtypes are attributes of the DataFrame. They provide information about the structure and data types of the DataFrame.")

print(df.columns)

print(df.index)

print(df.dtypes)

 here columns,index and dtypes are attributes of the DataFrame. They provide information about the structure and data types of the DataFrame.
Index(['Name', 'Age', 'Salary'], dtype='str')
RangeIndex(start=0, stop=3, step=1)
Name        str
Age       int64
Salary    int64
dtype: object

# 7. info()

`info()` gives important information about the DataFrame.

It shows:

- Number of rows
- Column names
- Non-null values
- Data types
- Memory usage

### Syntax

```python
df.info()

### the method info() provides a concise summary of the DataFrame, including the number of non-null entries, data types, and memory usage.

In [19]:


print("the method info() provides a concise summary of the DataFrame, including the number of non-null entries, data types, and memory usage.")
df.info()

the method info() provides a concise summary of the DataFrame, including the number of non-null entries, data types, and memory usage.
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Salary  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

# 8. describe()

`describe()` provides statistical information about numeric columns.

It commonly returns:

- count
- mean
- standard deviation
- minimum
- 25%
- 50%
- 75%
- maximum

In [20]:
df.describe()

             Age   Salary
count   3.000000      3.0
mean   27.666667  55000.0
std     2.516611   5000.0
min    25.000000  50000.0
25%    26.500000  52500.0
50%    28.000000  55000.0
75%    29.000000  57500.0
max    30.000000  60000.0

# 9. Selecting Columns

## Select One Column

Use:

```python
df["Name"]

In [21]:
df[["Name", "Salary"]]

    Name  Salary
0  Rahul   50000
1   Amit   60000
2    Raj   55000

One column   → df["Name"]

Multiple     → df[["Name", "Salary"]]

In [22]:


print(df["Name"])

0    Rahul
1     Amit
2      Raj
Name: Name, dtype: str

In [23]:
print(df[["Name", "Salary"]])

    Name  Salary
0  Rahul   50000
1   Amit   60000
2    Raj   55000

# 10. iloc

`iloc` is used to select data based on **integer position**.

### Examples

```python
df.iloc[0]

In [24]:
df.iloc[0:2]

    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000

In [25]:
df.iloc[0:2]

    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000

iloc → integer location
###  the iloc indexer is used to select rows and columns by their integer position in the DataFrame. It allows you to access specific rows and columns based on their numerical index rather than their labels

In [ ]:

print(" the iloc indexer is used to select rows and columns by their integer position in the DataFrame. It allows you to access specific rows and columns based on their numerical index rather than their labels.")
print(df.iloc[0])
print(df.iloc[0:2])

Name      Rahul
Age          25
Salary    50000
Name: 0, dtype: object
    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000

# 11. loc

`loc` is used to select data based on **index labels**.

### Example

```python
df.loc[0]

loc  → label
iloc → integer position

In [28]:

### the loc indexer is used to select rows and columns by their labels in the DataFrame. It allows you to access specific rows and columns based on their labels rather than their integer position.
print(df.loc[0])

Name      Rahul
Age          25
Salary    50000
Name: 0, dtype: object

# 12. Filtering Data

Filtering means selecting rows based on a condition.

### Example

Find employees whose salary is greater than 55000.

```python
df[df["Salary"] > 55000]

In [29]:


result = df[df["Salary"] > 55000]

print(result)

   Name  Age  Salary
1  Amit   30   60000

# 13. Multiple Conditions

We can combine multiple conditions.

### AND

Use:

```python
&

### Salary greater than 55000 AND Age greater than 25:

In [30]:
df[
    (df["Salary"] > 55000) &
    (df["Age"] > 25)
]

   Name  Age  Salary
1  Amit   30   60000

In [31]:


result = df[
    (df["Salary"] > 55000) &
    (df["Age"] > 25)
]

print(result)

   Name  Age  Salary
1  Amit   30   60000

# 14. Adding a New Column

We can create a new column by assigning a value.

### Example

```python
df["Bonus"] = 5000

In [53]:
df["Bonus"] = 5000

### We can also create a column using calculations.

In [54]:
print("Annual salary can be calculated by multiplying the monthly salary by 12. We can create a new column in the DataFrame to store the annual salary for each employee.")
df["AnnualSalary"] = df["Salary"] * 12
print(df)

Annual salary can be calculated by multiplying the monthly salary by 12. We can create a new column in the DataFrame to store the annual salary for each employee.
    Name  Age  Salary  AnnualSalary  Bonus
0  Rahul   25   50000        600000   5000
1   Amit   30   60000        720000   5000
2    Raj   28   55000        660000   5000

# 15. Sorting Data

`sort_values()` is used to sort a DataFrame.

### Ascending

```python
df.sort_values("Salary")

In [55]:
df.sort_values("Salary", ascending=False)

    Name  Age  Salary  AnnualSalary  Bonus
1   Amit   30   60000        720000   5000
2    Raj   28   55000        660000   5000
0  Rahul   25   50000        600000   5000


### 🐍 Python Cell

```python
print(df.sort_values("Salary"))

In [56]:
print(df.sort_values("Salary", ascending=False))

    Name  Age  Salary  AnnualSalary  Bonus
1   Amit   30   60000        720000   5000
2    Raj   28   55000        660000   5000
0  Rahul   25   50000        600000   5000

# 16. Rename and Drop

## Rename Column

```python
df.rename(
    columns={"Salary": "MonthlySalary"},
    inplace=True
)

### Delete Column

In [57]:
print(df.columns)

Index(['Name', 'Age', 'Salary', 'AnnualSalary', 'Bonus'], dtype='str')

In [58]:
df.drop("Bonus", axis=1, inplace=True)

In [60]:
print("Bonus is deleted from the DataFrame using the drop() method with axis=1 to indicate that we want to drop a column. The inplace=True argument modifies the DataFrame in place, so the Bonus column is removed from df.")
print(df.columns)

Bonus is deleted from the DataFrame using the drop() method with axis=1 to indicate that we want to drop a column. The inplace=True argument modifies the DataFrame in place, so the Bonus column is removed from df.
Index(['Name', 'Age', 'Salary', 'AnnualSalary'], dtype='str')

### Delete Row

In [38]:
df.drop(0, axis=0)

   Name  Age  Salary  AnnualSalary
1  Amit   30   60000        720000
2   Raj   28   55000        660000


### 🐍 Python Cell

```python
df.rename(
    columns={"Salary": "MonthlySalary"},
    inplace=True
)

print(df)

In [ ]:
df.drop("Bonus", axis=1, inplace=True)

print(df)

# 17. Missing Values

Missing values are commonly represented by `NaN`.

### Check Missing Values

```python
df.isnull()

### Count Missing Values

In [40]:
df.isnull().sum()

Name            0
Age             0
Salary          0
AnnualSalary    0
dtype: int64

### Fill Missing Values

In [41]:
df.fillna(0)

    Name  Age  Salary  AnnualSalary
0  Rahul   25   50000        600000
1   Amit   30   60000        720000
2    Raj   28   55000        660000

### Remove Missing Rows

In [42]:
df.dropna()

    Name  Age  Salary  AnnualSalary
0  Rahul   25   50000        600000
1   Amit   30   60000        720000
2    Raj   28   55000        660000


### 🐍 Python Cell

```python
data = {
    "Name": ["Rahul", "Amit", "Raj"],
    "Salary": [50000, None, 60000]
}

df_missing = pd.DataFrame(data)

print(df_missing)

In [61]:
data = {
    "Name": ["Rahul", "Amit", "Raj"],
    "Salary": [50000, None, 60000]
}

df_missing = pd.DataFrame(data)

print(df_missing)

    Name   Salary
0  Rahul  50000.0
1   Amit      NaN
2    Raj  60000.0

### here isnull() method is used to check for missing values in the DataFrame. It returns a DataFrame of the same shape as df_missing, where each element is True if the corresponding value is missing (NaN) and False otherwise. The sum() method is then applied to count the number of missing values in each column.

In [ ]:
### here isnull() method is used to check for missing values in the DataFrame. It returns a DataFrame of the same shape as df_missing, where each element is True if the corresponding value is missing (NaN) and False otherwise. The sum() method is then applied to count the number of missing values in each column.
print(df_missing.isnull())
### here sum method is used to count the number of missing values in each column
print(df_missing.isnull().sum())

Name      0
Salary    0
dtype: int64

## `isnull()` Quick Revision

| Method / Value | Meaning |
|---|---|
| `isnull()` | Finds missing values |
| `True` | Missing value (`NaN`) |
| `False` | Value is present / not missing |
| `sum()` | Counts the `True` values |
| `isnull().sum()` | Gives the number of missing values in each column |

### Remember

`isnull()` → **Find missing values**

`True` → **Missing**

`False` → **Not missing**

`sum()` → **Count True values**

`isnull().sum()` → **Count missing values column-wise**

In [65]:
df_missing["Salary"] = df_missing["Salary"].fillna(0)

print(df_missing)

    Name   Salary
0  Rahul  50000.0
1   Amit      0.0
2    Raj  60000.0

### 18 — Unique Values

# 18. unique(), nunique() and value_counts()

### unique()

Returns unique values.

```python
df["Name"].unique()

nunique()

Returns the number of unique values.

In [ ]:
df["Name"].nunique()

value_counts()

Counts how many times each value occurs.

In [67]:
df["Department"].value_counts()

KeyError: 'Department'

In [46]:

data = {
    "Name": ["Rahul", "Amit", "Rahul", "Raj", "Amit"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"]
}

df2 = pd.DataFrame(data)

print(df2["Name"].unique())

print(df2["Name"].nunique())

print(df2["Department"].value_counts())

<StringArray>
['Rahul', 'Amit', 'Raj']
Length: 3, dtype: str
3
Department
IT         2
HR         2
Finance    1
Name: count, dtype: int64

# 19. Reading CSV Files

Pandas can read CSV files using `read_csv()`.

### Syntax

```python
pd.read_csv("filename.csv")

In [68]:
df = pd.read_csv("employees.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'employees.csv'

# 20. Writing DataFrame to CSV

Use `to_csv()` to save a DataFrame as a CSV file.

### Syntax

```python
df.to_csv("output.csv", index=False)

### index=False prevents Pandas from saving the DataFrame index as an additional column.

In [48]:


df.to_csv("output.csv", index=False)

⭐ Quick Revision — Pandas Basics

# ⭐ Quick Revision — Pandas Basics

| # | Operation | Syntax | Purpose |
|---|---|---|---|
| 1 | Import Pandas | `import pandas as pd` | Import Pandas |
| 2 | Create Series | `pd.Series(data)` | Create 1-D data |
| 3 | Create DataFrame | `pd.DataFrame(data)` | Create table |
| 4 | First 5 rows | `df.head()` | View first 5 rows |
| 5 | First N rows | `df.head(n)` | View first N rows |
| 6 | Last 5 rows | `df.tail()` | View last 5 rows |
| 7 | Last N rows | `df.tail(n)` | View last N rows |
| 8 | Shape | `df.shape` | Get `(rows, columns)` |
| 9 | Column names | `df.columns` | Get column names |
| 10 | Row index | `df.index` | Get row labels |
| 11 | Data types | `df.dtypes` | Get data types |
| 12 | DataFrame info | `df.info()` | Structure + nulls + dtypes |
| 13 | Statistics | `df.describe()` | Statistical summary |
| 14 | One column | `df["Name"]` | Select one column |
| 15 | Multiple columns | `df[["Name","Salary"]]` | Select multiple columns |
| 16 | Select by position | `df.iloc[0]` | Select using integer position |
| 17 | Select by label | `df.loc[0]` | Select using label |
| 18 | Filter rows | `df[df["Salary"] > 50000]` | Apply condition |
| 19 | AND condition | `&` | Both conditions must be True |
| 20 | OR condition | `\|` | At least one condition True |
| 21 | Add column | `df["Bonus"] = 5000` | Create new column |
| 22 | Calculate column | `df["Annual"] = df["Salary"] * 12` | Create calculated column |
| 23 | Sort | `df.sort_values("Salary")` | Sort data |
| 24 | Descending sort | `df.sort_values("Salary", ascending=False)` | Highest → lowest |
| 25 | Rename | `df.rename(columns={"Salary":"Pay"})` | Rename column |
| 26 | Drop column | `df.drop("Bonus", axis=1)` | Delete column |
| 27 | Drop row | `df.drop(0, axis=0)` | Delete row |
| 28 | Missing values | `df.isnull()` | Find missing values |
| 29 | Count missing | `df.isnull().sum()` | Count missing values |
| 30 | Fill missing | `df.fillna(0)` | Replace missing values |
| 31 | Remove missing | `df.dropna()` | Remove rows with missing values |
| 32 | Unique values | `df["Dept"].unique()` | Get unique values |
| 33 | Number of unique | `df["Dept"].nunique()` | Count unique values |
| 34 | Frequency | `df["Dept"].value_counts()` | Count each value |
| 35 | Read CSV | `pd.read_csv("file.csv")` | Load CSV |
| 36 | Save CSV | `df.to_csv("file.csv", index=False)` | Save DataFrame |

---

# 🧠 Most Important Differences

| Concept | Remember |
|---|---|
| `head()` | First rows |
| `tail()` | Last rows |
| `shape` | Rows + columns |
| `columns` | Column names |
| `index` | Row labels |
| `dtypes` | Data types |
| `info()` | Structure of DataFrame |
| `describe()` | Statistics |
| `iloc` | **Integer Position** |
| `loc` | **Label** |
| `isnull()` | Where is missing? |
| `isnull().sum()` | How many missing? |
| `fillna()` | Fill missing values |
| `dropna()` | Remove missing values |
| `unique()` | What values exist? |
| `nunique()` | How many unique? |
| `value_counts()` | How many times each value occurs? |

---

# ⭐ Axis Memory Trick

| Axis | Meaning | Example |
|---|---|---|
| `axis=0` | Rows | `df.drop(0, axis=0)` |
| `axis=1` | Columns | `df.drop("Salary", axis=1)` |

### 🧠 Easy Trick

**axis=0 → down → rows**

**axis=1 → across → columns**

---

# ⭐ Selection Memory Trick

```python
df["Name"]

🎯 Final Pandas Memory Map

# 🎯 Final Pandas Memory Map

```text
PANDAS
│
├── 📌 CREATE
│   ├── Series
│   │   └── pd.Series(data)
│   │
│   └── DataFrame
│       └── pd.DataFrame(data)
│
├── 🔍 INSPECT
│   ├── head()       → First rows
│   ├── tail()       → Last rows
│   ├── shape        → Rows + Columns
│   ├── columns      → Column names
│   ├── index        → Row labels
│   ├── dtypes       → Data types
│   ├── info()       → Structure + nulls
│   └── describe()   → Statistics
│
├── 🎯 SELECT
│   ├── df["Name"]                → One column
│   ├── df[["Name", "Salary"]]    → Multiple columns
│   ├── iloc                      → Integer position
│   └── loc                       → Label
│
├── 🔎 FILTER
│   ├── > < == !=                 → Conditions
│   ├── &                         → AND
│   └── |                         → OR
│
├── ✏️ MODIFY
│   ├── Add column
│   │   └── df["Bonus"] = 5000
│   │
│   ├── rename()
│   │   └── Change column name
│   │
│   └── drop()
│       ├── axis=0 → Rows
│       └── axis=1 → Columns
│
├── 🧹 MISSING DATA
│   ├── isnull()       → Find missing
│   ├── isnull().sum() → Count missing
│   ├── fillna()       → Fill missing
│   └── dropna()       → Remove missing
│
├── 📊 ANALYSIS
│   ├── unique()       → What values?
│   ├── nunique()      → How many unique?
│   └── value_counts() → How many times?
│
├── 🔃 SORT
│   ├── sort_values()
│   ├── ascending=True  → Low → High
│   └── ascending=False → High → Low
│
└── 📁 FILE OPERATIONS
    ├── read_csv()      → Read CSV
    └── to_csv()        → Save CSV
```

## 🧠 Super Quick Memory

**CREATE → INSPECT → SELECT → FILTER → MODIFY → CLEAN → ANALYZE → SORT → SAVE**

### ⭐ Golden Rules

- `shape` → **Rows, Columns**
- `iloc` → **Integer Position**
- `loc` → **Label**
- `axis=0` → **Rows**
- `axis=1` → **Columns**
- `&` → **AND**
- `|` → **OR**
- `ascending=False` → **Descending**
- `inplace=True` → **Modify Original**
- `index=False` → **Don't save index**

# ⭐ Pandas Golden Rules

1. `shape` → **Rows, Columns**
2. `iloc` → **Integer Position**
3. `loc` → **Label**
4. `axis=0` → **Rows**
5. `axis=1` → **Columns**
6. `&` → **AND**
7. `|` → **OR**
8. `ascending=False` → **Descending Order**
9. `inplace=True` → **Modify the Original DataFrame**
10. `index=False` → **Do Not Save DataFrame Index in CSV**

## 🧠 Easy Memory Trick

| Pandas Concept | Remember |
|---|---|
| `shape` | Rows + Columns |
| `iloc` | Integer |
| `loc` | Label |
| `axis=0` | Rows |
| `axis=1` | Columns |
| `&` | AND |
| `|` | OR |
| `ascending=False` | High → Low |
| `inplace=True` | Change Original |
| `index=False` | No Index in CSV |

## ⭐ One-Line Memory

**Pandas = Create → Inspect → Select → Filter → Modify → Clean → Analyze → Save**