# Pandas

# 🐼 Pandas Basics

Pandas is a Python library used for:

- Data Analysis
- Data Cleaning
- Data Manipulation
- Reading and Writing CSV/Excel files
- Filtering and Sorting data
- Grouping data
- Handling Missing Values

## Important Pandas Objects

| Object | Description |
|--------|-------------|
| Series | One-dimensional data |
| DataFrame | Two-dimensional tabular data |

The standard way to import Pandas is:

```python
import pandas as pd

# 1. Series

A Series is a **one-dimensional labeled array**.

It is similar to a single column in an Excel sheet.

### Syntax

```python
pd.Series(data)

In [2]:

import pandas as pd


marks = pd.Series([80, 75, 90, 65])

print(marks)

0    80
1    75
2    90
3    65
dtype: int64

# 2. Series with Custom Index

We can provide our own index labels while creating a Series.

In [3]:
marks = pd.Series(
    [80, 75, 90],
    index=["Rahul", "Amit", "Raj"]
)

print(marks)

Rahul    80
Amit     75
Raj      90
dtype: int64

### Access Series Value

In [4]:
print(marks["Rahul"])

80

# 3. DataFrame

A DataFrame is a **two-dimensional table** containing rows and columns.

It is similar to an Excel spreadsheet or a database table.

### Example

| Name | Age | Salary |
|------|-----|--------|
| Rahul | 25 | 50000 |
| Amit | 30 | 60000 |
| Raj | 28 | 55000 |

In [5]:
data = {
    "Name": ["Rahul", "Amit", "Raj"],
    "Age": [25, 30, 28],
    "Salary": [50000, 60000, 55000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000
2    Raj   28   55000

## Understanding `pd.DataFrame(data)`

```python
df = pd.DataFrame(data)
pd.DataFrame(data)
│  │          │
│  │          └── Data we want to put into the table
│  └───────────── Creates a DataFrame
└──────────────── Pandas library


Here:

pd → Pandas library
DataFrame → Pandas class used to create a table
data → Data that we want to store in the DataFrame
df → Variable that stores the DataFrame

# 4. head() and tail()

### head()

`head()` displays the first 5 rows by default.

```python
df.head()

In [6]:
df.head(2)

    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000

### tail() displays the last 5 rows by default.

In [7]:
df.tail()

    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000
2    Raj   28   55000

### We can also specify the number:

In [8]:
df.tail(2)

   Name  Age  Salary
1  Amit   30   60000
2   Raj   28   55000

### Difference between head() and tail(): The head() method returns the first n rows of the DataFrame, while the tail() method returns the last n rows of the DataFrame. By default, both methods return 5 rows if no argument is provided.

In [12]:




print(df.head())
print("Now we can specify the number of rows to display using the head() method:")
print(df.head(2))
print(" We can also specify the number of rows to display using the tail() method:")
print(df.tail())
print("Difference between head() and tail(): The head() method returns the first n rows of the DataFrame, while the tail() method returns the last n rows of the DataFrame. By default, both methods return 5 rows if no argument is provided.")
print(df.tail(2))

    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000
2    Raj   28   55000
Now we can specify the number of rows to display using the head() method:
    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000
 We can also specify the number of rows to display using the tail() method:
    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000
2    Raj   28   55000
Difference between head() and tail(): The head() method returns the first n rows of the DataFrame, while the tail() method returns the last n rows of the DataFrame. By default, both methods return 5 rows if no argument is provided.
   Name  Age  Salary
1  Amit   30   60000
2   Raj   28   55000

# 5. shape

`shape` returns the number of rows and columns.

### Syntax

```python
df.shape

In [13]:
(3, 3)

(3, 3)

means:

3 rows
3 columns

# 6. columns, index and dtypes

### columns

Returns all column names.

```python
df.columns

index

Returns row indexes.

In [14]:
df.index

RangeIndex(start=0, stop=3, step=1)

dtypes

Returns the datatype of each column.

In [15]:
df.dtypes

Name        str
Age       int64
Salary    int64
dtype: object

### " here columns,index and dtypes are attributes of the DataFrame. They provide information about the structure and data types of the DataFrame."

In [18]:
print(" here columns,index and dtypes are attributes of the DataFrame. They provide information about the structure and data types of the DataFrame.")

print(df.columns)

print(df.index)

print(df.dtypes)

 here columns,index and dtypes are attributes of the DataFrame. They provide information about the structure and data types of the DataFrame.
Index(['Name', 'Age', 'Salary'], dtype='str')
RangeIndex(start=0, stop=3, step=1)
Name        str
Age       int64
Salary    int64
dtype: object

# 7. info()

`info()` gives important information about the DataFrame.

It shows:

- Number of rows
- Column names
- Non-null values
- Data types
- Memory usage

### Syntax

```python
df.info()

### the method info() provides a concise summary of the DataFrame, including the number of non-null entries, data types, and memory usage.

In [19]:


print("the method info() provides a concise summary of the DataFrame, including the number of non-null entries, data types, and memory usage.")
df.info()

the method info() provides a concise summary of the DataFrame, including the number of non-null entries, data types, and memory usage.
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Salary  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

# 8. describe()

`describe()` provides statistical information about numeric columns.

It commonly returns:

- count
- mean
- standard deviation
- minimum
- 25%
- 50%
- 75%
- maximum

In [20]:
df.describe()

             Age   Salary
count   3.000000      3.0
mean   27.666667  55000.0
std     2.516611   5000.0
min    25.000000  50000.0
25%    26.500000  52500.0
50%    28.000000  55000.0
75%    29.000000  57500.0
max    30.000000  60000.0

# 9. Selecting Columns

## Select One Column

Use:

```python
df["Name"]

In [21]:
df[["Name", "Salary"]]

    Name  Salary
0  Rahul   50000
1   Amit   60000
2    Raj   55000

One column   → df["Name"]

Multiple     → df[["Name", "Salary"]]

In [22]:


print(df["Name"])

0    Rahul
1     Amit
2      Raj
Name: Name, dtype: str

In [23]:
print(df[["Name", "Salary"]])

    Name  Salary
0  Rahul   50000
1   Amit   60000
2    Raj   55000

# 10. iloc

`iloc` is used to select data based on **integer position**.

### Examples

```python
df.iloc[0]

In [24]:
df.iloc[0:2]

    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000

In [25]:
df.iloc[0:2]

    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000

iloc → integer location
###  the iloc indexer is used to select rows and columns by their integer position in the DataFrame. It allows you to access specific rows and columns based on their numerical index rather than their labels

In [ ]:

print(" the iloc indexer is used to select rows and columns by their integer position in the DataFrame. It allows you to access specific rows and columns based on their numerical index rather than their labels.")
print(df.iloc[0])
print(df.iloc[0:2])

Name      Rahul
Age          25
Salary    50000
Name: 0, dtype: object
    Name  Age  Salary
0  Rahul   25   50000
1   Amit   30   60000

# 11. loc

`loc` is used to select data based on **index labels**.

### Example

```python
df.loc[0]

loc  → label
iloc → integer position

In [28]:

### the loc indexer is used to select rows and columns by their labels in the DataFrame. It allows you to access specific rows and columns based on their labels rather than their integer position.
print(df.loc[0])

Name      Rahul
Age          25
Salary    50000
Name: 0, dtype: object

# 12. Filtering Data

Filtering means selecting rows based on a condition.

### Example

Find employees whose salary is greater than 55000.

```python
df[df["Salary"] > 55000]

In [29]:


result = df[df["Salary"] > 55000]

print(result)

   Name  Age  Salary
1  Amit   30   60000

# 13. Multiple Conditions

We can combine multiple conditions.

### AND

Use:

```python
&

### Salary greater than 55000 AND Age greater than 25:

In [30]:
df[
    (df["Salary"] > 55000) &
    (df["Age"] > 25)
]

   Name  Age  Salary
1  Amit   30   60000

In [31]:


result = df[
    (df["Salary"] > 55000) &
    (df["Age"] > 25)
]

print(result)

   Name  Age  Salary
1  Amit   30   60000